### ISSUE TITLE
Works only partially

### ISSUE THREAD

**Issue by schaze** [Tieske/homie45#1] opened 2023-01-15 11:31 UTC
Hi Thijs, thanks for providing the script!
I does only work partially for me. Most devices are created under homie5 however many of the are missing the $description and $state topic. Also for many some properties seem to be randomly missing (in the topic structure - they are included in the $description json). Also forwarding set messages are not forwarded at all for none of the 10 devices I tested it with.

I do get a lot of warnings and errors from the script:

Warnings
(I guess these are epected as I am using the "eu.epnw.meta:1.1.0:4.0" extension to which these topics belong to)
```
Sun Jan 15 11:15:53 2023 WARN [homie45] 'homie/sensor-37' don't know how to handle topic 'homie/sensor-37/$meta/hc-controller/model-id/$value'
Sun Jan 15 11:15:53 2023 WARN [homie45] 'homie/sensor-4' don't know how to handle topic 'homie/sensor-4/$meta/hc-controller/device-fw/$key'
Sun Jan 15 11:15:53 2023 WARN [homie45] 'homie/sensor-4' don't know how to handle topic 'homie/sensor-4/$meta/hc-controller/device-fw/$value'
Sun Jan 15 11:15:53 2023 WARN [homie45] 'homie/sensor-4' don't know how to handle topic 'homie/sensor-4/$meta/hc-controller/device-mac/$key'
Sun Jan 15 11:15:53 2023 WARN [homie45] 'homie/sensor-4' don't know how to handle topic 'homie/sensor-4/$meta/hc-controller/device-mac/$value'
```

Errors (at the end of the output):
```
Sun Jan 15 11:16:28 2023 ERROR client 'homie45-bridge-123' failed to send PUBLISH: connector.send failed: failed acquiring send_lock: timeout
Sun Jan 15 11:16:28 2023 ERROR client 'homie45-bridge-123' failed to send PUBLISH: connector.send failed: failed acquiring send_lock: timeout
Sun Jan 15 11:16:28 2023 ERROR client 'homie45-bridge-123' failed to send PUBLISH: connector.send failed: failed acquiring send_lock: timeout
```

I am using vernemq for which the parameters should be tuned up enough for the corresponding settings you took for the eclipse mqtt.

DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES=15000
DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=100000
DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=100000

I do have a huge number of devices (homie4 shows about 12000 topics for all the devices).

also during the docker build I am getting several strange errors (build however finishes):

```
Step 6/17 : RUN luarocks install Tieske/luamqtt --dev
 ---> Running in dcbeb27dd5f1
Warning: Failed searching manifest: Failed downloading https://luarocks.org/dev/manifests/tieske/manifest-5.1 - HTTP/1.1 404 Not Found
Warning: Failed searching manifest: Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/dev/manifests/tieske/manifest-5.1 - HTTP/1.1 404 Not Found
Warning: Failed searching manifest: Failed downloading https://luafr.org/luarocks/dev/manifests/tieske/manifest-5.1 - HTTP/1.1 404 Not Found
Installing https://luarocks.org/manifests/tieske/luamqtt-scm-1.rockspec
Cloning into 'luamqtt'...
```

**Comment by Tieske** [comment] 2023-01-15 14:15
This very much looks like the exact same issue I had when setting the queue size 🤔 . I recall you mentioned you have a lot of devices, so many that a restart took a while because of all the topics.

Maybe I should build in a delay, when subscribing to a devices, wait at least for 2 seconds before subscribing to the next?


(the errors you can ignore; that's because I use development versions, not published ones)

**Comment by Tieske** [comment] 2023-01-15 14:17
also; any errors in the logs?

**Comment by schaze** [comment] 2023-01-15 15:13
So I tried it with a local mosquitto server and subset of my devices (about 51 devices with ~3000 topics). This one works nicely. no more "send_lock: timeout" messages and the /set topic relay works. Also as far as I can see all topics are there. 
The new protocol reduces the total amount of topics down to about 300! Much more reasonable IMHO :)
I am not familiar with lua, with regards to real thread parallelism. I use mainly nodejs which has only one main thread, so even if it does async work nothing really happens actually in parallel - but even with this I had to do some sensible rate limiting when publishing to mqtt. Maybe you can process the devices in batches of 5-10 in parallel only - this is what I usually did.

**Comment by schaze** [comment] 2023-01-15 15:14
> also; any errors in the logs?

Only the ones listed above from your script - nothing in the mqtt logs out of the ordinary

**Comment by Tieske** [comment] 2023-01-16 14:17
just pushed a fix (attempt). It has an extra parameter now;
```
export HOMIE_SUBSCRIBE_DELAY=1000
```
Which is the delay, in ms, of subscribing to topics of newly discovered v4 devices.

Can you give that a try?

**Comment by schaze** [comment] 2023-01-17 16:34
Thanks, with the delay it works nicely now. Only the disconnected devices are missing the $description and $state topics. 
v4:
![image](https://user-images.githubusercontent.com/4409163/212957387-6f0e7fff-3bf6-4237-b3ed-9ecbbf7c286c.png)
v5:
![image](https://user-images.githubusercontent.com/4409163/212957270-02bedda7-de6e-4d34-9d56-76fb25f83e9c.png)

**Comment by Tieske** [comment] 2023-01-17 23:25
That is correct. It will wait for a "first time seen 'ready'" situation, and only then will publish the description.

So by design. Let me know if you think this should be done differently

**Comment by schaze** [comment] 2023-01-18 17:43
I would either skip it completely or publish everything (preference is always publish no matter the $state). 
The way it currently works you do already have the property values published but they cannot be used since there is not metadata to understand them.

**Comment by Tieske** [comment] 2023-01-21 00:10
I pushed a fix today, should work like that now.

**Closed as completed** 2023-02-15 17:32 UTC
